version: 2.1

jobs:
  # Build
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package
      - persist_to_workspace:
          root: ./
          paths:
            - target/
  # Unit Test
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvnw test
  # Integration Test
  integration-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvnw integration-test
  # Deploy
  deploy-snapshot:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvnw deploy -s .circleci/settings.xml
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - integration-test:
          requires:
            - test
      - deploy-snapshot:
          requires:
            - integration-test
