version: 2.1

jobs:
  # Build
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - persist_to_workspace:
            root: .
            paths:
              - ./target
      - run: mvn -Dmaven.test.skip=true package
  # Unit Test
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: mvn test
  # Integration Test
  integration-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: mvn integration-test
  # Deploy
  deploy-snapshot:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: mvn deploy -s .circleci/settings.xml
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - integration-test:
          requires:
            - test
      - deploy-snapshot:
          requires:
            - integration-test
