version: 2.1

jobs:
  # Build
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - save_cache:
            paths:
              - ~/.m2
            key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn -Dmaven.test.skip=true package
  # Unit Test
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
      - run: mvn -Dmaven.test.skip=true package
      - run: mvn test
      - run: mvn integration-test
  # Deploy
  deploy-snapshot:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: mvn deploy -s .circleci/settings.xml
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-snapshot:
          requires:
            - test
